name: Deploy to EasyPanel on PR Merge to Main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy-on-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Trigger EasyPanel deploy
        run: |
          curl -X POST http://89.117.151.155:3000/api/deploy/3c508afc3f48f2a3251cf2fcfc605b0962fc33848c19c8ad
